fishingmod.AddCatch{
	friendly = "Junk",
	type = "prop_physics",
	models = {
		"models/props_junk/Shoe001a.mdl",
		"models/props_junk/garbage_coffeemug001a.mdl",
		"models/props_junk/garbage_coffeemug001a_chunk01.mdl",
		"models/props_junk/garbage_glassbottle001a.mdl",
		"models/props_junk/garbage_glassbottle001a_chunk01.mdl",
		"models/props_junk/garbage_glassbottle003a.mdl",
		"models/props_junk/garbage_metalcan001a.mdl",
		"models/props_junk/garbage_milkcarton001a.mdl",
		"models/props_junk/garbage_metalcan002a.mdl",
		"models/props_junk/garbage_milkcarton001a.mdl",
		"models/props_junk/garbage_milkcarton002a.mdl",
		"models/props_junk/garbage_newspaper001a.mdl",
		"models/props_junk/garbage_plasticbottle001a.mdl",
		"models/props_junk/garbage_plasticbottle002a.mdl",
		"models/props_junk/garbage_plasticbottle003a.mdl",
		"models/props_junk/garbage_takeoutcarton001a.mdl",
		"models/props_junk/GlassBottle01a.mdl",
		"models/props_junk/glassbottle01a_chunk01a.mdl",
		"models/props_junk/glassjug01.mdl",
		"models/props_junk/glassjug01_chunk02.mdl",
		"models/props_junk/PopCan01a.mdl",
		"models/props_junk/PropaneCanister001a.mdl",
		"models/props_junk/propane_tank001a.mdl",		
	},
	size = 10,
	rareness = 2000, 
	yank = 1000, 
	force = 2000, 
	mindepth = 0, 
	maxdepth = 500,
	remove_on_release = true,
}