fishingmod.AddCatch{
	friendly = "Junk",
	type = "prop_physics",
	models = {
		"models/props_junk/Shoe001a.mdl",
		"models/props_junk/garbage_coffeemug001a.mdl",
		"models/props_junk/garbage_coffeemug001a_chunk01.mdl",
		"models/props_junk/garbage_glassbottle001a.mdl",
		"models/props_junk/garbage_glassbottle001a_chunk01.mdl",
		"models/props_junk/garbage_glassbottle003a.mdl",
		"models/props_junk/garbage_metalcan001a.mdl",
		"models/props_junk/garbage_milkcarton001a.mdl",
		"models/props_junk/garbage_metalcan002a.mdl",
		"models/props_junk/garbage_milkcarton001a.mdl",
		"models/props_junk/garbage_milkcarton002a.mdl",
		"models/props_junk/garbage_newspaper001a.mdl",
		"models/props_junk/garbage_plasticbottle001a.mdl",
		"models/props_junk/garbage_plasticbottle002a.mdl",
		"models/props_junk/garbage_plasticbottle003a.mdl",
		"models/props_junk/garbage_takeoutcarton001a.mdl",
		"models/props_junk/GlassBottle01a.mdl",
		"models/props_junk/glassbottle01a_chunk01a.mdl",
		"models/props_junk/glassjug01.mdl",
		"models/props_junk/glassjug01_chunk02.mdl",
		"models/props_junk/PopCan01a.mdl",
		"models/props_junk/PropaneCanister001a.mdl",
		"models/props_junk/propane_tank001a.mdl",
		"models/props_junk/CinderBlock01a.mdl",
		"models/props_junk/vent001_chunk6.mdl",
		"models/props_junk/vent001_chunk7.mdl",
		"models/props_junk/vent001_chunk8.mdl",
		"models/props_c17/canisterchunk01a.mdl",
		"models/props_c17/canisterchunk02a.mdl",
		"models/props_borealis/door_wheel001a.mdl",
		"models/props_c17/FurnitureChair001a_Chunk01.mdl",
		"models/props_c17/FurnitureChair001a_Chunk02.mdl",
		"models/props_c17/FurnitureChair001a_Chunk03.mdl",
		"models/props_c17/TrapPropeller_Lever.mdl",
		"models/props_canal/mattpipe.mdl",
		"models/props_c17/metalPot001a.mdl",
		"models/props_c17/metalPot002a.mdl",
		"models/props_lab/box01a.mdl",
		"models/props_junk/cardboard_box004a.mdl",
		"models/props_junk/garbage_bag001a.mdl",
		"models/Gibs/metal_gib1.mdl",
		"models/Gibs/metal_gib2.mdl",
		"models/Gibs/metal_gib3.mdl",
		"models/Gibs/metal_gib4.mdl",
		"models/Gibs/metal_gib5.mdl",
		"models/props_wasteland/prison_pipefaucet001a.mdl",
	},
	size = 10,
	rareness = 2000, 
	yank = 1000, 
	mindepth = 0, 
	maxdepth = 20000,
	expgain = 20,
	levelrequired = 0,
	remove_on_release = true,
	bait = "none",
	value = 5,
}
