fishingmod.AddCatch{
	friendly = "Furniture Props",
	type = "prop_physics",
	models = {
		"models/props_c17/bench01a.mdl",
		"models/props_c17/FurnitureBathtub001a.mdl",
		"models/props_c17/FurnitureFridge001a.mdl",
		"models/props_c17/FurnitureCouch001a.mdl",
		"models/props_c17/FurnitureCouch002a.mdl",
		"models/props_c17/FurnitureSink001a.mdl",
		"models/props_c17/FurnitureTable001a.mdl",
		"models/props_c17/FurnitureTable002a.mdl",
		"models/props_c17/FurnitureTable003a.mdl",
		"models/props_c17/FurnitureToilet001a.mdl",
		"models/props_c17/FurnitureWashingmachine001a.mdl",
		"models/props_c17/shelfunit01a.mdl",
		"models/props_combine/breenchair.mdl",
		"models/props_combine/breendesk.mdl",
		"models/props_combine/breenglobe.mdl",
		"models/props_combine/breenclock.mdl",
		"models/props_interiors/BathTub01a.mdl",
		"models/props_interiors/Furniture_chair01a.mdl",
		"models/props_c17/chair02a.mdl",
		"models/props_interiors/Furniture_chair03a.mdl",
		"models/props_interiors/Furniture_Couch01a.mdl",
		"models/props_interiors/Furniture_Couch02a.mdl",
		"models/props_interiors/Furniture_Desk01a.mdl",
		"models/props_interiors/Furniture_Lamp01a.mdl",
		"models/props_interiors/Furniture_shelf01a.mdl",
		"models/props_interiors/Furniture_Vanity01a.mdl",
		"models/props_interiors/Furniture_CabinetDrawer01a.mdl",
		"models/props_interiors/Furniture_CabinetDrawer02a.mdl",
		"models/props_interiors/SinkKitchen01a.mdl",
		"models/props_junk/TrashBin01a.mdl",
		"models/props_junk/TrafficCone001a.mdl",
		"models/props_junk/PlasticCrate01a.mdl",
		"models/props_lab/kennel_physics.mdl",
		"models/props_trainstation/BenchOutdoor01a.mdl",
		"models/props_trainstation/bench_indoor001a.mdl",
		"models/props_trainstation/trashcan_indoor001a.mdl",
		"models/props_trainstation/trashcan_indoor001b.mdl",
		"models/props_wasteland/controlroom_filecabinet001a.mdl",
		"models/props_wasteland/controlroom_desk001a.mdl",
		"models/props_wasteland/controlroom_desk001b.mdl",
		"models/props_wasteland/controlroom_chair001a.mdl",
		"models/props_wasteland/controlroom_filecabinet002a.mdl",
		"models/props_wasteland/kitchen_stove001a.mdl",
		"models/props_wasteland/laundry_cart001.mdl",
		"models/props_wasteland/laundry_cart002.mdl",
		"models/props_wasteland/prison_bedframe001b.mdl",
		"models/props_c17/Frame002a.mdl",
		"models/props_c17/FurnitureArmchair001a.mdl",
		"models/props_c17/chair_kleiner03a.mdl",
		"models/props_c17/chair_office01a.mdl",
		"models/props_c17/chair_stool01a.mdl",
	},
	size = 10,
	rareness = 1000, 
	yank = 1000, 
	mindepth = 0, 
	maxdepth = 20000,
	expgain = 50,
	levelrequired = 60,
	value = 50,
	remove_on_release = true,
	bait = {
		"models/props_junk/sawblade001a.mdl",
	},
}
