fishingmod.AddCatch{
	friendly = "Building Props",
	type = "prop_physics",
	models = {
		"models/props_building_details/Storefront_Template001a_Bars.mdl",
		"models/props_borealis/bluebarrel001.mdl",
		"models/props_c17/concrete_barrier001a.mdl",
		"models/props_c17/concrete_barrier001a.mdl",
		"models/props_debris/metal_panel01a.mdl",
		"models/props_debris/metal_panel02a.mdl",
		"models/props_junk/wood_pallet001a.mdl",
		"models/props_lab/blastdoor001a.mdl",
		"models/props_lab/blastdoor001b.mdl",
		"models/props_lab/blastdoor001c.mdl",
		"models/props_junk/TrashDumpster02b.mdl",
		"models/props_wasteland/wood_fence01a.mdl",
		"models/props_wasteland/wood_fence02a.mdl",
		"models/props_c17/door01_left.mdl",
		"models/props_doors/door03_slotted_left.mdl",
		"models/props_wasteland/prison_celldoor001b.mdl",
		"models/props_junk/wood_crate001a.mdl",
		"models/props_junk/wood_crate001a_damaged.mdl",
		"models/props_junk/wood_crate002a.mdl",
	},
	size = 10,
	rareness = 1000, 
	yank = 1000, 
	mindepth = 0, 
	maxdepth = 20000,
	expgain = 50,
	levelrequired = 60,
	value = 50,
	remove_on_release = true,
	bait = {
		"models/props_c17/tools_wrench01a.mdl",
	},
}

