--disabled for now

--[[fishingmod.AddCatch{
	friendly = "Weapons",
	type = {
		"weapon_crowbar",
		"weapon_pistol",
		"weapon_smg1",
		"weapon_frag",
		"weapon_physcannon",
		"weapon_crossbow",
		"weapon_shotgun",
		"weapon_357",
		"weapon_rpg",
		"weapon_ar2",
		"gmod_tool",
		"gmod_camera",
		"weapon_physgun",
		"weapon_fishing_rod",
		"weapon_stunstick",
	},
	rareness = 1500, 
	yank = 150, 
	force = 0, 
	mindepth = 200, 
	maxdepth = 20000,
	remove_on_release = false,
	friendlybait = "Ammo",
	bait = {
		"models/Items/357ammo.mdl",
		"models/Items/357ammobox.mdl",
		"models/Items/grenadeAmmo.mdl",
		"models/Items/combine_rifle_ammo01.mdl",
		"models/Items/BoxBuckshot.mdl",
		"models/Items/BoxMRounds.mdl",
		"models/Items/BoxFlares.mdl",
		"models/Items/AR2_Grenade.mdl",
	},
}

fishingmod.AddCatch{
	friendly = "Weapons",
	type = {
		"Pistol", 
		"SMG1", 
		"grenade", 
		"Buckshot", 
		"357", 
		"XBowBolt", 
		"AR2Fire", 
		"rpg_round",
		"AR2AltFire", 
		"smg1_grenade", 
		"slam", 
	},
	rareness = 1500, 
	yank = 150, 
	force = 0, 
	mindepth = 200, 
	maxdepth = 20000,
	remove_on_release = false,
	friendlybait = "weapons",
	bait = {
		"models/weapons/w_crowbar.mdl", 
		"models/weapons/w_pistol.mdl",
		"models/weapons/w_smg1.mdl",
		"models/weapons/w_grenade.mdl",
		"models/weapons/w_physcannon.mdl", 
		"models/weapons/w_crossbow.mdl",
		"models/weapons/w_shotgun.mdl",
		"models/weapons/w_357.mdl",
		"models/weapons/w_rpg.mdl",
		"models/weapons/w_irifle.mdl",
		"models/weapons/w_toolgun.mdl", 
		"models/weapons/w_pistol.mdl",
		"models/weapons/w_superphyscannon.mdl",
		"models/weapons/w_stunstick.mdl",
	},
}]]